-- Auto-generated by gen_seed.py — do not hand-edit; regenerate from JSON.
-- ruleset = BB2025   teams = 5   distinct skills = 23
begin;

-- skills ---------------------------------------------------------------
insert into bb.skill (name) values
  ('Always Hungry'),
  ('Animal Savagery'),
  ('Animosity'),
  ('Block'),
  ('Brawler'),
  ('Dodge'),
  ('Frenzy'),
  ('Grab'),
  ('Jump Up'),
  ('Loner'),
  ('Mighty Blow'),
  ('No Ball'),
  ('Pick-me-up'),
  ('Prehensile Tail'),
  ('Projectile Vomit'),
  ('Really Stupid'),
  ('Regeneration'),
  ('Right Stuff'),
  ('Stunty'),
  ('Tackle'),
  ('Thick Skull'),
  ('Throw Team-mate'),
  ('Titchy')
on conflict (name) do nothing;

-- Black Orc ---------------------------------------------------
insert into bb.team (ruleset_id, name, gw_tier, reroll_cost, allows_apothecary, active, leagues, special_rules, notes) values (
  'BB2025', 'Black Orc', 3, 60000, true, true, array['Badlands Brawl']::text[], array['Brawlin'' Brutes', 'Bribery and Corruption']::text[], null
) on conflict (ruleset_id, name) do update set
  gw_tier = excluded.gw_tier, reroll_cost = excluded.reroll_cost,
  allows_apothecary = excluded.allows_apothecary, active = excluded.active,
  leagues = excluded.leagues, special_rules = excluded.special_rules,
  notes = excluded.notes;
insert into bb.positional (team_id, title, cost, ma, st, ag, pa, av, max_count, is_lineman, primary_access, secondary_access, group_id, can_be_raised) values (
  (select id from bb.team where ruleset_id = 'BB2025' and name = 'Black Orc'), 'Trained Troll', 115000, 4, 5, 5, 5, 10, 1, false, array['S']::text[], array['A', 'G', 'P']::text[], null, false
) on conflict (team_id, title) do update set
  cost = excluded.cost, ma = excluded.ma, st = excluded.st,
  ag = excluded.ag, pa = excluded.pa, av = excluded.av,
  max_count = excluded.max_count, is_lineman = excluded.is_lineman,
  primary_access = excluded.primary_access,
  secondary_access = excluded.secondary_access,
  group_id = excluded.group_id, can_be_raised = excluded.can_be_raised;
delete from bb.positional_skill where positional_id = (select id from bb.positional where title = 'Trained Troll' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Black Orc'));
insert into bb.positional_skill (positional_id, skill) values
  ((select id from bb.positional where title = 'Trained Troll' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Black Orc')), 'Always Hungry'),
  ((select id from bb.positional where title = 'Trained Troll' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Black Orc')), 'Mighty Blow'),
  ((select id from bb.positional where title = 'Trained Troll' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Black Orc')), 'Projectile Vomit'),
  ((select id from bb.positional where title = 'Trained Troll' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Black Orc')), 'Really Stupid'),
  ((select id from bb.positional where title = 'Trained Troll' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Black Orc')), 'Regeneration'),
  ((select id from bb.positional where title = 'Trained Troll' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Black Orc')), 'Throw Team-mate');
insert into bb.positional (team_id, title, cost, ma, st, ag, pa, av, max_count, is_lineman, primary_access, secondary_access, group_id, can_be_raised) values (
  (select id from bb.team where ruleset_id = 'BB2025' and name = 'Black Orc'), 'Black orc', 90000, 4, 4, 4, 5, 10, 6, false, array['G', 'S']::text[], array['A', 'D']::text[], null, false
) on conflict (team_id, title) do update set
  cost = excluded.cost, ma = excluded.ma, st = excluded.st,
  ag = excluded.ag, pa = excluded.pa, av = excluded.av,
  max_count = excluded.max_count, is_lineman = excluded.is_lineman,
  primary_access = excluded.primary_access,
  secondary_access = excluded.secondary_access,
  group_id = excluded.group_id, can_be_raised = excluded.can_be_raised;
delete from bb.positional_skill where positional_id = (select id from bb.positional where title = 'Black orc' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Black Orc'));
insert into bb.positional_skill (positional_id, skill) values
  ((select id from bb.positional where title = 'Black orc' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Black Orc')), 'Brawler'),
  ((select id from bb.positional where title = 'Black orc' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Black Orc')), 'Grab');
insert into bb.positional (team_id, title, cost, ma, st, ag, pa, av, max_count, is_lineman, primary_access, secondary_access, group_id, can_be_raised) values (
  (select id from bb.team where ruleset_id = 'BB2025' and name = 'Black Orc'), 'Goblin Bruiser', 45000, 6, 2, 3, 4, 8, null, true, array['A', 'D']::text[], array['G', 'P', 'S']::text[], null, false
) on conflict (team_id, title) do update set
  cost = excluded.cost, ma = excluded.ma, st = excluded.st,
  ag = excluded.ag, pa = excluded.pa, av = excluded.av,
  max_count = excluded.max_count, is_lineman = excluded.is_lineman,
  primary_access = excluded.primary_access,
  secondary_access = excluded.secondary_access,
  group_id = excluded.group_id, can_be_raised = excluded.can_be_raised;
delete from bb.positional_skill where positional_id = (select id from bb.positional where title = 'Goblin Bruiser' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Black Orc'));
insert into bb.positional_skill (positional_id, skill) values
  ((select id from bb.positional where title = 'Goblin Bruiser' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Black Orc')), 'Dodge'),
  ((select id from bb.positional where title = 'Goblin Bruiser' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Black Orc')), 'Right Stuff'),
  ((select id from bb.positional where title = 'Goblin Bruiser' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Black Orc')), 'Stunty'),
  ((select id from bb.positional where title = 'Goblin Bruiser' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Black Orc')), 'Thick Skull');

-- Chaos Renegades ---------------------------------------------
insert into bb.team (ruleset_id, name, gw_tier, reroll_cost, allows_apothecary, active, leagues, special_rules, notes) values (
  'BB2025', 'Chaos Renegades', 3, 70000, true, true, array['Chaos Clash']::text[], array['Favoured of...']::text[], 'Imported from Blood Bowl Base — check against your own copy.'
) on conflict (ruleset_id, name) do update set
  gw_tier = excluded.gw_tier, reroll_cost = excluded.reroll_cost,
  allows_apothecary = excluded.allows_apothecary, active = excluded.active,
  leagues = excluded.leagues, special_rules = excluded.special_rules,
  notes = excluded.notes;
insert into bb.positional_group (team_id, name, max_count) values (
  (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades'), 'Big Guys', 3
) on conflict (team_id, name) do update set max_count = excluded.max_count;
insert into bb.positional (team_id, title, cost, ma, st, ag, pa, av, max_count, is_lineman, primary_access, secondary_access, group_id, can_be_raised) values (
  (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades'), 'Rat Ogre', 150000, 6, 5, 4, 6, 9, 1, false, array['S']::text[], array['A', 'G', 'M']::text[], (select id from bb.positional_group where name = 'Big Guys' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades')), false
) on conflict (team_id, title) do update set
  cost = excluded.cost, ma = excluded.ma, st = excluded.st,
  ag = excluded.ag, pa = excluded.pa, av = excluded.av,
  max_count = excluded.max_count, is_lineman = excluded.is_lineman,
  primary_access = excluded.primary_access,
  secondary_access = excluded.secondary_access,
  group_id = excluded.group_id, can_be_raised = excluded.can_be_raised;
delete from bb.positional_skill where positional_id = (select id from bb.positional where title = 'Rat Ogre' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades'));
insert into bb.positional_skill (positional_id, skill) values
  ((select id from bb.positional where title = 'Rat Ogre' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades')), 'Animal Savagery'),
  ((select id from bb.positional where title = 'Rat Ogre' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades')), 'Frenzy'),
  ((select id from bb.positional where title = 'Rat Ogre' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades')), 'Loner'),
  ((select id from bb.positional where title = 'Rat Ogre' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades')), 'Mighty Blow'),
  ((select id from bb.positional where title = 'Rat Ogre' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades')), 'Prehensile Tail');
insert into bb.positional (team_id, title, cost, ma, st, ag, pa, av, max_count, is_lineman, primary_access, secondary_access, group_id, can_be_raised) values (
  (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades'), 'Troll', 115000, 4, 5, 5, 5, 10, 1, false, array['S']::text[], array['A', 'G', 'M', 'P']::text[], (select id from bb.positional_group where name = 'Big Guys' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades')), false
) on conflict (team_id, title) do update set
  cost = excluded.cost, ma = excluded.ma, st = excluded.st,
  ag = excluded.ag, pa = excluded.pa, av = excluded.av,
  max_count = excluded.max_count, is_lineman = excluded.is_lineman,
  primary_access = excluded.primary_access,
  secondary_access = excluded.secondary_access,
  group_id = excluded.group_id, can_be_raised = excluded.can_be_raised;
delete from bb.positional_skill where positional_id = (select id from bb.positional where title = 'Troll' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades'));
insert into bb.positional_skill (positional_id, skill) values
  ((select id from bb.positional where title = 'Troll' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades')), 'Always Hungry'),
  ((select id from bb.positional where title = 'Troll' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades')), 'Loner'),
  ((select id from bb.positional where title = 'Troll' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades')), 'Mighty Blow'),
  ((select id from bb.positional where title = 'Troll' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades')), 'Projectile Vomit'),
  ((select id from bb.positional where title = 'Troll' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades')), 'Really Stupid'),
  ((select id from bb.positional where title = 'Troll' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades')), 'Regeneration'),
  ((select id from bb.positional where title = 'Troll' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades')), 'Throw Team-mate');
insert into bb.positional (team_id, title, cost, ma, st, ag, pa, av, max_count, is_lineman, primary_access, secondary_access, group_id, can_be_raised) values (
  (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades'), 'Renegade Goblin', 40000, 6, 2, 3, 4, 8, null, true, array['A', 'D', 'M']::text[], array['G', 'P']::text[], null, false
) on conflict (team_id, title) do update set
  cost = excluded.cost, ma = excluded.ma, st = excluded.st,
  ag = excluded.ag, pa = excluded.pa, av = excluded.av,
  max_count = excluded.max_count, is_lineman = excluded.is_lineman,
  primary_access = excluded.primary_access,
  secondary_access = excluded.secondary_access,
  group_id = excluded.group_id, can_be_raised = excluded.can_be_raised;
delete from bb.positional_skill where positional_id = (select id from bb.positional where title = 'Renegade Goblin' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades'));
insert into bb.positional_skill (positional_id, skill) values
  ((select id from bb.positional where title = 'Renegade Goblin' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades')), 'Animosity'),
  ((select id from bb.positional where title = 'Renegade Goblin' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades')), 'Dodge'),
  ((select id from bb.positional where title = 'Renegade Goblin' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades')), 'Right Stuff'),
  ((select id from bb.positional where title = 'Renegade Goblin' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Chaos Renegades')), 'Stunty');

-- Human -------------------------------------------------------
insert into bb.team (ruleset_id, name, gw_tier, reroll_cost, allows_apothecary, active, leagues, special_rules, notes) values (
  'BB2025', 'Human', 1, 50000, true, true, array['Old World Classic']::text[], array['Team Captain']::text[], 'Imported from Blood Bowl Base — check against your own copy.'
) on conflict (ruleset_id, name) do update set
  gw_tier = excluded.gw_tier, reroll_cost = excluded.reroll_cost,
  allows_apothecary = excluded.allows_apothecary, active = excluded.active,
  leagues = excluded.leagues, special_rules = excluded.special_rules,
  notes = excluded.notes;
insert into bb.positional (team_id, title, cost, ma, st, ag, pa, av, max_count, is_lineman, primary_access, secondary_access, group_id, can_be_raised) values (
  (select id from bb.team where ruleset_id = 'BB2025' and name = 'Human'), 'Human Blitzer', 85000, 7, 3, 3, 4, 9, 2, false, array['G', 'S']::text[], array['A', 'D']::text[], null, false
) on conflict (team_id, title) do update set
  cost = excluded.cost, ma = excluded.ma, st = excluded.st,
  ag = excluded.ag, pa = excluded.pa, av = excluded.av,
  max_count = excluded.max_count, is_lineman = excluded.is_lineman,
  primary_access = excluded.primary_access,
  secondary_access = excluded.secondary_access,
  group_id = excluded.group_id, can_be_raised = excluded.can_be_raised;
delete from bb.positional_skill where positional_id = (select id from bb.positional where title = 'Human Blitzer' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Human'));
insert into bb.positional_skill (positional_id, skill) values
  ((select id from bb.positional where title = 'Human Blitzer' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Human')), 'Block'),
  ((select id from bb.positional where title = 'Human Blitzer' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Human')), 'Tackle');
insert into bb.positional (team_id, title, cost, ma, st, ag, pa, av, max_count, is_lineman, primary_access, secondary_access, group_id, can_be_raised) values (
  (select id from bb.team where ruleset_id = 'BB2025' and name = 'Human'), 'Human Lineman', 50000, 6, 3, 3, 4, 9, null, true, array['G']::text[], array['A', 'D', 'S']::text[], null, false
) on conflict (team_id, title) do update set
  cost = excluded.cost, ma = excluded.ma, st = excluded.st,
  ag = excluded.ag, pa = excluded.pa, av = excluded.av,
  max_count = excluded.max_count, is_lineman = excluded.is_lineman,
  primary_access = excluded.primary_access,
  secondary_access = excluded.secondary_access,
  group_id = excluded.group_id, can_be_raised = excluded.can_be_raised;
delete from bb.positional_skill where positional_id = (select id from bb.positional where title = 'Human Lineman' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Human'));
insert into bb.positional (team_id, title, cost, ma, st, ag, pa, av, max_count, is_lineman, primary_access, secondary_access, group_id, can_be_raised) values (
  (select id from bb.team where ruleset_id = 'BB2025' and name = 'Human'), 'Halfling Hopeful', 30000, 5, 2, 3, 4, 7, null, true, array['A']::text[], array['D', 'G', 'S']::text[], null, false
) on conflict (team_id, title) do update set
  cost = excluded.cost, ma = excluded.ma, st = excluded.st,
  ag = excluded.ag, pa = excluded.pa, av = excluded.av,
  max_count = excluded.max_count, is_lineman = excluded.is_lineman,
  primary_access = excluded.primary_access,
  secondary_access = excluded.secondary_access,
  group_id = excluded.group_id, can_be_raised = excluded.can_be_raised;
delete from bb.positional_skill where positional_id = (select id from bb.positional where title = 'Halfling Hopeful' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Human'));
insert into bb.positional_skill (positional_id, skill) values
  ((select id from bb.positional where title = 'Halfling Hopeful' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Human')), 'Dodge'),
  ((select id from bb.positional where title = 'Halfling Hopeful' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Human')), 'Right Stuff'),
  ((select id from bb.positional where title = 'Halfling Hopeful' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Human')), 'Stunty');

-- Norse -------------------------------------------------------
insert into bb.team (ruleset_id, name, gw_tier, reroll_cost, allows_apothecary, active, leagues, special_rules, notes) values (
  'BB2025', 'Norse', 1, 60000, true, true, array['Chaos Clash', 'Old World Classic']::text[], array['Favoured of...']::text[], 'Imported from Blood Bowl Base — check against your own copy.'
) on conflict (ruleset_id, name) do update set
  gw_tier = excluded.gw_tier, reroll_cost = excluded.reroll_cost,
  allows_apothecary = excluded.allows_apothecary, active = excluded.active,
  leagues = excluded.leagues, special_rules = excluded.special_rules,
  notes = excluded.notes;
insert into bb.positional (team_id, title, cost, ma, st, ag, pa, av, max_count, is_lineman, primary_access, secondary_access, group_id, can_be_raised) values (
  (select id from bb.team where ruleset_id = 'BB2025' and name = 'Norse'), 'Norse Berserker', 90000, 6, 3, 3, 5, 8, 2, false, array['G', 'S']::text[], array['A', 'P']::text[], null, false
) on conflict (team_id, title) do update set
  cost = excluded.cost, ma = excluded.ma, st = excluded.st,
  ag = excluded.ag, pa = excluded.pa, av = excluded.av,
  max_count = excluded.max_count, is_lineman = excluded.is_lineman,
  primary_access = excluded.primary_access,
  secondary_access = excluded.secondary_access,
  group_id = excluded.group_id, can_be_raised = excluded.can_be_raised;
delete from bb.positional_skill where positional_id = (select id from bb.positional where title = 'Norse Berserker' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Norse'));
insert into bb.positional_skill (positional_id, skill) values
  ((select id from bb.positional where title = 'Norse Berserker' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Norse')), 'Block'),
  ((select id from bb.positional where title = 'Norse Berserker' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Norse')), 'Frenzy'),
  ((select id from bb.positional where title = 'Norse Berserker' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Norse')), 'Jump Up');
insert into bb.positional (team_id, title, cost, ma, st, ag, pa, av, max_count, is_lineman, primary_access, secondary_access, group_id, can_be_raised) values (
  (select id from bb.team where ruleset_id = 'BB2025' and name = 'Norse'), 'Beer Boar', 20000, 5, 1, 3, null, 6, 2, false, '{}'::text[], array['A']::text[], null, false
) on conflict (team_id, title) do update set
  cost = excluded.cost, ma = excluded.ma, st = excluded.st,
  ag = excluded.ag, pa = excluded.pa, av = excluded.av,
  max_count = excluded.max_count, is_lineman = excluded.is_lineman,
  primary_access = excluded.primary_access,
  secondary_access = excluded.secondary_access,
  group_id = excluded.group_id, can_be_raised = excluded.can_be_raised;
delete from bb.positional_skill where positional_id = (select id from bb.positional where title = 'Beer Boar' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Norse'));
insert into bb.positional_skill (positional_id, skill) values
  ((select id from bb.positional where title = 'Beer Boar' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Norse')), 'Dodge'),
  ((select id from bb.positional where title = 'Beer Boar' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Norse')), 'No Ball'),
  ((select id from bb.positional where title = 'Beer Boar' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Norse')), 'Pick-me-up'),
  ((select id from bb.positional where title = 'Beer Boar' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Norse')), 'Stunty'),
  ((select id from bb.positional where title = 'Beer Boar' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Norse')), 'Titchy');

-- Dark Elf ----------------------------------------------------
insert into bb.team (ruleset_id, name, gw_tier, reroll_cost, allows_apothecary, active, leagues, special_rules, notes) values (
  'BB2025', 'Dark Elf', 1, 50000, true, true, array['Elven Kingdoms League']::text[], '{}'::text[], 'Imported from Blood Bowl Base — check against your own copy.'
) on conflict (ruleset_id, name) do update set
  gw_tier = excluded.gw_tier, reroll_cost = excluded.reroll_cost,
  allows_apothecary = excluded.allows_apothecary, active = excluded.active,
  leagues = excluded.leagues, special_rules = excluded.special_rules,
  notes = excluded.notes;
insert into bb.positional (team_id, title, cost, ma, st, ag, pa, av, max_count, is_lineman, primary_access, secondary_access, group_id, can_be_raised) values (
  (select id from bb.team where ruleset_id = 'BB2025' and name = 'Dark Elf'), 'Witch Elf', 110000, 7, 3, 2, 4, 8, 2, false, array['A', 'G']::text[], array['S', 'D']::text[], null, false
) on conflict (team_id, title) do update set
  cost = excluded.cost, ma = excluded.ma, st = excluded.st,
  ag = excluded.ag, pa = excluded.pa, av = excluded.av,
  max_count = excluded.max_count, is_lineman = excluded.is_lineman,
  primary_access = excluded.primary_access,
  secondary_access = excluded.secondary_access,
  group_id = excluded.group_id, can_be_raised = excluded.can_be_raised;
delete from bb.positional_skill where positional_id = (select id from bb.positional where title = 'Witch Elf' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Dark Elf'));
insert into bb.positional_skill (positional_id, skill) values
  ((select id from bb.positional where title = 'Witch Elf' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Dark Elf')), 'Dodge'),
  ((select id from bb.positional where title = 'Witch Elf' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Dark Elf')), 'Frenzy'),
  ((select id from bb.positional where title = 'Witch Elf' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Dark Elf')), 'Jump Up');
insert into bb.positional (team_id, title, cost, ma, st, ag, pa, av, max_count, is_lineman, primary_access, secondary_access, group_id, can_be_raised) values (
  (select id from bb.team where ruleset_id = 'BB2025' and name = 'Dark Elf'), 'Dark Elf Lineman', 65000, 6, 3, 2, 3, 9, null, true, array['A', 'G']::text[], array['S', 'D']::text[], null, false
) on conflict (team_id, title) do update set
  cost = excluded.cost, ma = excluded.ma, st = excluded.st,
  ag = excluded.ag, pa = excluded.pa, av = excluded.av,
  max_count = excluded.max_count, is_lineman = excluded.is_lineman,
  primary_access = excluded.primary_access,
  secondary_access = excluded.secondary_access,
  group_id = excluded.group_id, can_be_raised = excluded.can_be_raised;
delete from bb.positional_skill where positional_id = (select id from bb.positional where title = 'Dark Elf Lineman' and team_id = (select id from bb.team where ruleset_id = 'BB2025' and name = 'Dark Elf'));

commit;
