#!/usr/bin/env python3
"""
Generate idempotent seed SQL for the bb.* reference catalogue from a
Blood Bowl teams JSON export (the Sevens-project format).

Usage:
    python3 gen_seed.py teams.json > 02_seed_bb.sql
    python3 gen_seed.py teams.json --ruleset BB2025 > 02_seed_bb.sql

The output:
  * upserts every team, group, positional and starting skill,
  * is safe to re-run (ON CONFLICT ... DO UPDATE; skills are rebuilt
    per positional so fixing the JSON and re-running converges),
  * writes gw_tier straight from the JSON `tier` field (take-as-current),
  * leaves caps exactly as-is (NULL = 0-16), pa NULL where absent.

It does NOT delete teams/positionals removed from the JSON — remove those
in the Supabase table editor if needed.
"""
import argparse
import json
import sys

# Canonicalise known spelling/spacing variants to one skill name.
SKILL_CANON = {
    "Throw Team-Mate": "Throw Team-mate",
    "Throw Team-mate": "Throw Team-mate",
    "Throw Team-mate.": "Throw Team-mate",
    "Side Step": "Sidestep",
}


def canon_skill(raw):
    s = (raw or "").strip()
    if s in ("", "-"):
        return None
    return SKILL_CANON.get(s, s)


def lit(s):
    if s is None:
        return "null"
    return "'" + str(s).replace("'", "''") + "'"


def num(n):
    return "null" if n is None else str(int(n))


def boollit(b):
    return "true" if b else "false"


def arr(items):
    items = items or []
    if not items:
        return "'{}'::text[]"
    return "array[" + ", ".join(lit(x) for x in items) + "]::text[]"


def team_ref(ruleset, name):
    return f"(select id from bb.team where ruleset_id = {lit(ruleset)} and name = {lit(name)})"


def group_ref(ruleset, team, group):
    if not group:
        return "null"
    return ("(select id from bb.positional_group where name = " + lit(group) +
            " and team_id = " + team_ref(ruleset, team) + ")")


def positional_ref(ruleset, team, title):
    return ("(select id from bb.positional where title = " + lit(title) +
            " and team_id = " + team_ref(ruleset, team) + ")")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("--ruleset", default="BB2025")
    args = ap.parse_args()

    with open(args.input, encoding="utf-8") as fh:
        teams = json.load(fh)

    rs = args.ruleset
    out = []
    w = out.append

    # collect canonical skills across every positional
    all_skills = set()
    canon_warnings = []
    for t in teams:
        for p in t.get("positionals", []):
            for raw in p.get("skills", []):
                cs = canon_skill(raw)
                if cs:
                    all_skills.add(cs)
                    if cs != (raw or "").strip():
                        canon_warnings.append(f"{t['name']} / {p['title']}: "
                                              f"{raw!r} -> {cs!r}")

    w("-- Auto-generated by gen_seed.py — do not hand-edit; regenerate from JSON.")
    w(f"-- ruleset = {rs}   teams = {len(teams)}   distinct skills = {len(all_skills)}")
    w("begin;")
    w("")

    # 1) skill dictionary
    w("-- skills ---------------------------------------------------------------")
    w("insert into bb.skill (name) values")
    w(",\n".join("  (" + lit(s) + ")" for s in sorted(all_skills)))
    w("on conflict (name) do nothing;")
    w("")

    # 2) teams, groups, positionals, skills
    for t in teams:
        name = t["name"]
        w(f"-- {name} " + "-" * max(1, 60 - len(name)))
        w("insert into bb.team "
          "(ruleset_id, name, gw_tier, reroll_cost, allows_apothecary, active, "
          "leagues, special_rules, notes) values (")
        w("  " + ", ".join([
            lit(rs), lit(name), num(t.get("tier")), num(t.get("reroll_cost")),
            boollit(t.get("allows_apothecary", True)),
            boollit(t.get("active", True)),
            arr(t.get("leagues")), arr(t.get("special_rules")),
            lit(t.get("notes")),
        ]))
        w(") on conflict (ruleset_id, name) do update set")
        w("  gw_tier = excluded.gw_tier, reroll_cost = excluded.reroll_cost,")
        w("  allows_apothecary = excluded.allows_apothecary, active = excluded.active,")
        w("  leagues = excluded.leagues, special_rules = excluded.special_rules,")
        w("  notes = excluded.notes;")

        for g in t.get("groups", []):
            w("insert into bb.positional_group (team_id, name, max_count) values (")
            w("  " + ", ".join([team_ref(rs, name), lit(g["name"]),
                                num(g.get("max_count"))]))
            w(") on conflict (team_id, name) do update set max_count = excluded.max_count;")

        for p in t.get("positionals", []):
            title = p["title"]
            w("insert into bb.positional "
              "(team_id, title, cost, ma, st, ag, pa, av, max_count, is_lineman, "
              "primary_access, secondary_access, group_id, can_be_raised) values (")
            w("  " + ", ".join([
                team_ref(rs, name), lit(title), num(p.get("cost")),
                num(p.get("ma")), num(p.get("st")), num(p.get("ag")),
                num(p.get("pa")), num(p.get("av")), num(p.get("max_count")),
                boollit(p.get("is_lineman", False)),
                arr(p.get("primary")), arr(p.get("secondary")),
                group_ref(rs, name, p.get("group")),
                boollit(p.get("can_be_raised", False)),
            ]))
            w(") on conflict (team_id, title) do update set")
            w("  cost = excluded.cost, ma = excluded.ma, st = excluded.st,")
            w("  ag = excluded.ag, pa = excluded.pa, av = excluded.av,")
            w("  max_count = excluded.max_count, is_lineman = excluded.is_lineman,")
            w("  primary_access = excluded.primary_access,")
            w("  secondary_access = excluded.secondary_access,")
            w("  group_id = excluded.group_id, can_be_raised = excluded.can_be_raised;")

            # rebuild this positional's starting skills (declarative)
            skills = sorted({canon_skill(s) for s in p.get("skills", [])} - {None})
            pref = positional_ref(rs, name, title)
            w(f"delete from bb.positional_skill where positional_id = {pref};")
            if skills:
                w("insert into bb.positional_skill (positional_id, skill) values")
                w(",\n".join(f"  ({pref}, {lit(s)})" for s in skills) + ";")
        w("")

    w("commit;")

    if canon_warnings:
        sys.stderr.write("Skill names canonicalised:\n")
        for line in canon_warnings:
            sys.stderr.write("  " + line + "\n")

    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
